# Generated by Django 3.0.2 on 2020-01-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists_api', '0005_auto_20200121_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='/profIcon/defo.png', max_length=100),
        ),
    ]
