# Generated by Django 3.0.2 on 2020-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists_api', '0006_auto_20200121_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='/image/profIcon/defo.png', max_length=100),
        ),
    ]
