# Generated by Django 3.0.2 on 2020-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errdepo_api', '0004_auto_20200118_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='profIcon/defo.png', max_length=100),
        ),
    ]
